### ISSUE TITLE
Could a client component import a server component?

### ISSUE THREAD

**Issue by shmuli9** [epicweb-dev/react-server-components#10]
I wasn't clear on this paragraph in part 3, (this [file](https://github.com/epicweb-dev/react-server-components/edit/main/exercises/03.client-components/README.mdx)):

> In fact, that `import` for the `./server-component.js` module would even work in
> the client. That module could have secret environment variables or a database
> connection etc.

Is it supposed to read:

> In fact, that `import` for the `./server-component.js` module would **_not_** even work in
> the client. That module could have secret environment variables or a database
> connection etc.

Or am I misunderstanding something here?

**Comment by kentcdodds** [comment]
You're understanding correctly. That's missing a crucial word!

**Comment by kentcdodds** [comment]
Fixed!
