### ISSUE TITLE
what is encodeReply doing?

### ISSUE THREAD

**Issue by lili21** [epicweb-dev/react-server-components#2]
we just need to send the formData to server right? why do we need to encode it.

**Comment by kentcdodds** [comment]
Technically we have full control of what happens in the `callServer` function so we could do that. Unfortunately, `args` will sometimes be the `formData` and other times it'll `[previouslyReturnedValue, newFormData]` (which is the case for us in our example) (I really hate this a lot).

After diving into `encodeReply`, I discovered it also handles React elements (🧐), promises, sets, regular objects, and somehow functions (converts them to references). It's doing a lot and I'm still working out exactly what the use cases for all of this are. It could be there's room to expand this particular exercise a bit to dive into these use cases further. I'm not sure how deep I want to go on it though, especially with how experimental this bit is currently.

In any case, I'm going to close this issue, but feel free to reply if you have a follow-up.
