### ISSUE TITLE
Avoid global db

### ISSUE THREAD

**Issue by mcollina** [epicweb-dev/react-server-components#6]
Currently, this recommends the use of a global db and connection pool.
This makes individual testing harder, as one must rely on module mocking.

I've recently been working on a slightly different approach using AsyncLocalStorage.
I've put it in a tiny module for ease of use: https://github.com/mcollina/asyncforge/blob/main/asyncforge.js#L32-L56.

The key idea is to store the db connection pool (and all other needed part of the app) attached to the AsyncLocalStorage.

```js
import { memo } from 'asyncforge'

export const db = memo('db')
export function buildDB () { ... }
```

Then, 

```js
import { db, buildDB } from './db.js'

db.set(await buildDB())
```

However in tests one could do:

```js
import { test } from 'node:test'
import { buildDB } from './db.js'

test('my db', async () => {
  const db = await buildDB()
})
```

To use (in React and others):

```js
import { db } from './db.js'

export function myFn () {
  return db().query(...)
}
```

This is essentially identical to Next.js `headers()` helpers etc.

**Comment by kentcdodds** [comment]
Thanks @mcollina! This is intended to be as simple as possible. Optimizations are distractions in this project.

But I appreciate you spending the time to make a PR and open this issue! You're always a great help!
